name: Preview docs in PR

on:
  pull_request:
    branches:
        - main
    types:
        - ready_for_review

env:
  UV_VERSION: 0.6
  PYTHON_VERSION: 3.12

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Check mkdocs build
        run: |
          uv run \
            --with 'nomad-lab[infrastructure] @ https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git' \
            mkdocs build --strict --site-dir site

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site
